
# this will only handle static python and js tests
---
name: Static Tests
on:
  - push
jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
          npm run build-prod
      - name: Run Jest Tests
        run: npm run jest-travis
...
